### ISSUE TITLE
Please, merge fixes from jaqx0r/afero

### ISSUE THREAD

**Issue by TheTincho** [spf13/afero#105]
Not sure why this did not happen yet, but I am dealing with a user of this library (mtail) which is depending on the fork to avoid some bugs apparently fixed there. Could you merge those?

Thanks

**Comment by moorereason** [comment]
This issue should be closed.  mtail is using spf13/afero.  jaqx0r fixes were merged in 40ffa2c25cafb4db322e0b9b4c93d31d273dabe8.
