### ISSUE TITLE
MemFS doesn't set permissions on create/mkdir

### ISSUE THREAD

**Issue by ashb** [spf13/afero#107]
I discovered that the MemMapFS doesn't store the permissions you might pass to `OpenFile` which makes this FS behave differently to an OFS one, at least in terms of that value you get back out of `Stat()`.

**Update**: The problem is that permissions passed to Mkdir and OpenFile are not set - if I do a Chmod afterwards they are set correctly.

**Comment by mbertschler** [comment]
Should be fixed by #110
