### ISSUE TITLE
Lack of documentation and initializer on many fs implementations

### ISSUE THREAD

**Issue by xiegeo** [spf13/afero#117]
When reading though the documentation, I noticed many **public** filesystem implementations without either documentation or initialization. It turns out the implementations all implement the fs interface, and are initialized only as fs interface so they are not grouped together in the documentation, which take a bit of jumping though documentation and mentally matching interfaces.

I realize once I know that, it does not impend usage of afero as much; but it is still a strange pattern.

I think either the implementations should be private (best for a clean documentation), initializations should return the concrete type (if there is a use case for that), or some documentation to clarify the strangeness.

**Comment by moorereason** [comment]
Duplicate of #76.

**Comment by xiegeo** [comment]
Thanks, it looks like the way to fix #76 will also fix this problem. Namely, organizing the documentation clearly.
