### ISSUE TITLE
Tagged releases?

### ISSUE THREAD

**Issue by hausdorff** [spf13/afero#129]
I want to vendor this as a dependency in a library I'm writing, but I've noticed that there are no releases tagged, so it's really difficult to know what the best place to set HEAD to is.

Perusing the git log, it looks like releases are "tagged" in commit messages, and the last one was more than a year ago. It seems like a lot of progress has been made since then, though, so I'm reticent to track back to 0.10.

So, I propose:
* The authors push tags to the repository.
* The authors publish another release.

**Comment by bep** [comment]
There is now a v1.0.0
