### ISSUE TITLE
dep ensure -v

### ISSUE THREAD

**Issue by jason4wy** [spf13/afero#163]
Solving failure: No versions of github.com/spf13/afero met constraints:
	v1.1.0: unable to deduce repository and source type for "golang.org/x/text/transform": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/text/transform?go-get=1": Get http://golang.org/x/text/transform?go-get=1: dial tcp 216.239.37.1:80: getsockopt: connection refused
	v1.0.2: unable to deduce repository and source type for "golang.org/x/text/transform": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/text/transform?go-get=1": Get http://golang.org/x/text/transform?go-get=1: dial tcp 216.239.37.1:80: getsockopt: connection refused
	v1.0.1: unable to deduce repository and source type for "golang.org/x/text/transform": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/text/transform?go-get=1": Get http://golang.org/x/text/transform?go-get=1: dial tcp 216.239.37.1:80: getsockopt: connection refused
	v1.0.0: unable to deduce repository and source type for "golang.org/x/text/transform": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/text/transform?go-get=1": Get http://golang.org/x/text/transform?go-get=1: dial tcp 216.239.37.1:80: getsockopt: connection refused
	master: unable to deduce repository and source type for "golang.org/x/text/transform": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/text/transform?go-get=1": Get http://golang.org/x/text/transform?go-get=1: dial tcp 216.239.37.1:80: getsockopt: connection refused
	jaqx0r-patch-1: unable to deduce repository and source type for "golang.org/x/text/transform": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/text/transform?go-get=1": Get http://golang.org/x/text/transform?go-get=1: dial tcp 216.239.37.1:80: getsockopt: connection refused
	lstater: unable to deduce repository and source type for "golang.org/x/text/transform": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/text/transform?go-get=1": Get http://golang.org/x/text/transform?go-get=1: dial tcp 216.239.37.1:80: getsockopt: connection refused
	return-concrete-types: unable to deduce repository and source type for "golang.org/x/text/transform": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://golang.org/x/text/transform?go-get=1": Get http://golang.org/x/text/transform?go-get=1: dial tcp 216.239.37.1:80: getsockopt: connection refused

**Comment by mbertschler** [comment]
What is your problem and what are the steps to reproduce this?

**Comment by donglei** [comment]
have the same promble,just dep add dependency
`dep ensure -add github.com/spf13/viper`
