### ISSUE TITLE
MemMapFs.Mkdir() does not return error when it should

### ISSUE THREAD

**Issue by malkhamis** [spf13/afero#164]
It is expected that creating a directory in a nonexistent path using `Mkdir()` with `OsFS` returns an error. However, trying that with the `MemMapFs` does not return an error as shown in the example below.

```
package main

import (
	"fmt"

	"github.com/spf13/afero"
)

func main() {

	osFS := afero.NewOsFs()
	err := osFS.Mkdir("/tmp/nested/dir", 0)
	fmt.Println(err)
	// output: mkdir /tmp/nested/dir: no such file or directory

	memFS := afero.NewMemMapFs()
	err = memFS.Mkdir("/tmp/nested/dir", 0)
	fmt.Println(err)
	// output: <nil>

}
```

It seems there is a missing check [in here](https://github.com/spf13/afero/blob/63644898a8da0bc22138abf860edaf5277b6102e/memmap.go#L128) for whether the path of the new directory exists before proceeding with creating the directory.

**Comment by whilei** [comment]
A related error/non-error is that it will not error when `MkdirAll`ing above an existing file:

```go
memFS := afero.NewMemMapFS()
f, err := afero.TempFile(memFS, "", "")
if err != nil {
	panic(err)
}
err = memFS.MkdirAll(filepath.Join(f.Name(), "dirOnTopOfFile")
if err == nil {
	panic("should be mkdir: f1/file.txt/f2: Not a directory")
}
```

**Comment by aviau** [comment]
This test fails:
```
func TestMeMapStat(t *testing.T) {
	fs := filesystem.NewMemMapFS()
	_, err := fs.Stat("")
	assert.Error(t, err)
}
```

**Comment by kargakis** [comment]
Duplicate of https://github.com/spf13/afero/issues/149
