### ISSUE TITLE
Consider allowing other maintainers or moving to a github organization

### ISSUE THREAD

**Issue by aviau** [spf13/afero#165]
Hello!

Would you consider allowing other maintainers or moving to a github organization?

There are a number of pull requests that date about two years and that have not gotten responses.

If there was an afero organization on github, it could contain several repositories with file system implementation packages. You wouldn't have to merge them in  the main repository and it would help the community organize around something.

You could keep control of the main repository but give commit access to people in other repositories inside the github organization.

**Comment by aviau** [comment]
//cc @spf13 @bep

**Comment by bep** [comment]
I'm not the owner of this repo, but I agree in principle. I can just say that I have more than enough repositories to maintain as it is.

**Comment by spf13** [comment]
I would love additional maintainers

**Comment by aviau** [comment]
I think that if you want more maintainers, you should encourage people contributing by reviewing pull requests. Maybe you could also add a message in the README, asking for people to step up and help.

**Comment by JoshuaKolden** [comment]
It seems like maintainers here are overwhelmed with other projects. To help with ongoing bug fixes and feature implementation I created a new github organization called AbsFS.  AbsFS's primary goal is to create a new abstract filesystem package for go, using some of the best ideas of Afero and other filesystem abstraction packages.

AbsFS will also maintain a fork of Afero to allow the Afero community to give back by providing ongoing maintenance and support.  The `AbsFS/Afero` repos will not supersede `spf13/Afero`, but with the approval of the `spf13/Afero` maintainers, updates from AbsFS/Afero may find there way into this repo. 

If you have pending issues, or Pull Requests please come join AbsFS and add those issues and pull requests there. 

[AbsFS/afero](https://github.com/AbsFS/afero)

@spf13, @bep, @aviau

**Comment by kargakis** [comment]
I can help out with any reviews for now. Not sure this issue needs to be open anymore so closing, feel free to open if you think otherwise.
