### ISSUE TITLE
Afero can't handle relative paths properly

### ISSUE THREAD

**Issue by mbertschler** [spf13/afero#20]
This code:
``` go
package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/afero"
)

func main() {
	fs := new(afero.MemMapFs)

	f, _ := fs.Create(filepath.Join(".", "file"))
	f.WriteString("TestFile content")
	f.Close()

	wd, _ := os.Getwd()

	_, err := fs.Open(filepath.Join(wd, "file"))
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println("wd:", wd)

	fs.List()
}
```

Produces this output:
```
$ absrel
file does not exist
wd: /tmp
file 16
. 42
```

It doesn't make sense to save relative paths into the MemMapFs, they all should be absolute.

I am working on a fix for that problem, but I am not sure if this can work together with the working directory from the os package. The problem is that if I use `os.Chdir("/tmp/afero")`, and then create a file "./file" on OS X it is actually put into "/private/tmp/afero". So if I use the dir string that I used in the Chdir function, the file is also not found. I also can't always use `filepath.EvalSymlinks` because files that exist in a MemMapFs won't exist in the real file system.

**Comment by moorereason** [comment]
The current behavior makes complete sense to me.  The `MemMapFs` starts from scratch at the root of a new, clean filesystem.  The "working directory" is always `/`.  Creating `./file` should create `/file`.  Relative paths appear to work just fine.

`MemMapFs` does not pay attention to the OS working directory (technically, neither does `OsFs` except for the fact that the `os` stdlib package takes care of it for you).  I think what you're really wanting is to add `Chdir` and `Getwd` to the `afero.Fs` interface.

Also, I'm confused by your last paragraph.  Are you expecting the `MemMapFs` to act as an overlay on the current OS filesystem?  If so, I think you're asking for #39.

**Comment by mbertschler** [comment]
This bug was filed when afero tried to open the "." dir. The main problem here has actually been solved.
I thought of a feature where folders in `MemMapFs` would mirror os folders, so that for example /tmp on OSX would become /private/tmp. The thing is I am not sure if that makes sense anymore of if that would be something that actually benefits a real world program. 

As the main problem here is solved I am closing this.
