### ISSUE TITLE
File extension for afero.TempFile

### ISSUE THREAD

**Issue by aswinkarthik** [spf13/afero#217]
Currently, we are unable to set file extension for a temp file that is created using `afero.TempFile`. In `ioutil.TempFile` we are able to do so by specifying the pattern like `prefix-*.yml`, the temp file will be created with a random string at the last `*`. Refer [here](https://golang.org/pkg/io/ioutil/#TempFile)

Can `afero.TempFile` also do a similar replacement?  If this change can be accepted, will love to raise a PR.

**Comment by nithyanatarajan** [comment]
@spf13 We are also in need of the feature. I have raised a PR for the same. Kindly have a look at it.

**Comment by kargakis** [comment]
Fixed by https://github.com/spf13/afero/pull/229
