### ISSUE TITLE
mem file should adjust f.at on calling Truncate

### ISSUE THREAD

**Issue by TimSatke** [spf13/afero#235]
Currently, I use `Truncate(0)` to `empty` a memory file. However, it seems like, if the file had 12 bytes of content (so `f.at == 13`), and I call `Truncate(0)`, `f.at` is still `13`, which causes the next write, to write 13 `0x00`-bytes before the actually written content.
https://github.com/spf13/afero/blob/master/mem/file.go#L214

```go
file.WriteString("hello")
// file content is []byte{'h', 'e', 'l', 'l', 'o'}
file.Truncate(0)
// len(f.fileData.data) == 0
file.WriteString("hello")
// file content is []byte{0x00, 0x00, 0x00, 0x00, 0x00, 'h', 'e', 'l', 'l', 'o'}
```

Is this an actual bug, or am I using `Truncate` wrong?

**Comment by TimSatke** [comment]
Workaround so far is to add
```go
_, _ = f.file.Seek(0, io.SeekStart)
```
after calling `file.Truncate(0)`

**Comment by kargakis** [comment]
Golang does not seem to use Seek in its own Truncate call so it is probably wise to stay consistent.

https://golang.org/src/os/file_unix.go?s=9408:9452#L297

**Comment by TimSatke** [comment]
Yes, just saw that too today. Thank you.
