### ISSUE TITLE
go 1.16 compatibility 

### ISSUE THREAD

**Issue by xakep666** [spf13/afero#275]
It seems that future releases of go will bring us new io/fs package with some interfaces for file system (https://tip.golang.org/pkg/io/fs). 
Is it possible to make afero compatible with io/fs?

**Comment by VoyTechnology** [comment]
Based on a quick investigation, it looks like the only place where a change might be needed is

```go
type File interface {
    Stat(name string) (os.FileInfo, error) // return fs.FileInfo instead
}
```

However, also looking at `os` package it looks like it would be still working fine without changing it.

```go
type FileInfo = fs.FileInfo
```

**Comment by cugu** [comment]
`afero` uses `afero.File` while `fs` uses `fs.File`, which are quite different so this would require some refactoring.

A simple example:
```golang
info, _ := fs.Stat(afero.NewMemMapFs(), ".")
fmt.Println(info)
```
results in
```
./main.go:12:38: cannot use afero.NewMemMapFs() (type afero.Fs) as type fs.FS in argument to fs.Stat:
	afero.Fs does not implement fs.FS (wrong type for Open method)
		have Open(string) (afero.File, error)
		want Open(string) (fs.File, error)
```
