### ISSUE TITLE
Greek translation

### ISSUE THREAD

**Issue by robbyt** [spf13/afero#28]
In modern Greek, aferimenos (αφηρημένος) means abstract (as an adjective), and afairo (αφαιρώ) is pronounced like "afero", but it means to subtract.

**Comment by spf13** [comment]
Interesting, Thanks for adding this. I love words and so many of our english words have roots in Greek (and latin). 

After seeing your post I decided to research the etymology further and I really liked what I found.

Afero comes from the latin roots Ad-Facere. 
It's analogous to the modern english "affair".

However even more interesting is that the roots connote even more.
"Ad" is a prefix meaning to
and 
"Facere" is a form of the root "faciō" making make or do. 
This is the root for a lot of other english words:
Factory, Fact, benefactor, fortification, gratification, sanctification, scientific, effect ... 

So I should revise the readme, but Afero is actually a pretty great name for an abstract library that allows one to make and manipulate files on a lot of different places. 

It's also nice that unlike some of my other libraries (hugo, cobra, viper) it googles very well.
