### ISSUE TITLE
Error with go 1.10 version: looking for io/fs: Cannot detect VCS

### ISSUE THREAD

**Issue by yogi2606** [spf13/afero#294]
I am using 
- package: github.com/spf13/viper
  version: v1.4.0
- package: github.com/spf13/cobra
  version: 0.0.5
  
which internally using spf13/afero  package

I am using go 1.10 and getting following error

`[0;33m[WARN] [mUnable to checkout io/fs
[0;31m[ERROR] [mError looking for io/fs: Cannot detect VCS
[0;31m[ERROR] [mFailed to retrieve a list of dependencies: Error resolving imports
make: *** [dependencies] Error 1
`

i drill down to root cause and found that one of the package from
- package: github.com/spf13/viper
  version: v1.4.0
- package: github.com/spf13/cobra
  version: 0.0.5
  
 is downloading latest version of spf13/afero which is compatible with go 1.16 only

**Comment by jeffwidman** [comment]
You'll need `go 1.15.10` or higher, see https://github.com/spf13/afero/pull/291#issuecomment-807324649

**Comment by jcburley** [comment]
> You'll need `go 1.15.10` or higher, see [#291 (comment)](https://github.com/spf13/afero/pull/291#issuecomment-807324649)

Is there a reason `go.mod` has not been updated to require Go 1.15 (or 1.16)? Seems like it should be, since the package itself now requires that.

**Comment by jeffwidman** [comment]
Good suggestion @jcburley, I just opened #346 to address that.
