### ISSUE TITLE
Vulnerable version of https://github.com/pkg/sftp

### ISSUE THREAD

**Issue by avtrifanov** [spf13/afero#301]
Hi!
It seems that you are using the vulnerable version of https://github.com/pkg/sftp [package](https://github.com/spf13/afero/blob/master/go.mod#L4).  Its version 1.10.1 is vulnerable to DoS. You can find more details [here](https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMPKGSFTP-569475).
You should update to version 1.11.0 or higher to fix this.

**Comment by jxsl13** [comment]
#312 seems to solve this
This issue can be closed.

**Comment by avtrifanov** [comment]
Great, thanks for the fix:)
