### ISSUE TITLE
Hugo build is broken on Windows

### ISSUE THREAD

**Issue by bep** [spf13/afero#31]
Looks to be Afero-related, and it happened recently.

See https://github.com/spf13/hugo/issues/1680

**Comment by mbertschler** [comment]
Probably also related to this issue #26.
I fear I can't help with this because I have no access to a Windows machine until wednesday.

For now I added an AppVeyor config to this repo that we can test our future changes on Windows too and asked @spf13 to integrate it. #30

**Comment by spf13** [comment]
https://ci.appveyor.com/project/spf13/afero

**Comment by spf13** [comment]
I'll do my best to fix this tomorrow. Have been a bit sick lately, but hopefully will be able to fix it up.
