### ISSUE TITLE
Upgrade github.com/pkg/sftp dependency to >= 1.11.0

### ISSUE THREAD

**Issue by martinmpoirier** [spf13/afero#315]
Hi,

I am using cobra latest release at the moment (1.2.1) and it refers to viper which refers to afero and lastly to pkg/sftp the current version is 1.10.1 and it gets flag as a security warning by Nexus IQ (https://github.com/pkg/sftp/issues/308).  

Increasing to the version of pkg/sftp 1.11 or later would resolve this security warning.

Thank you for your great work !

**Comment by kargakis** [comment]
Fixed by https://github.com/spf13/afero/pull/312
