### ISSUE TITLE
[Question] How to listen to file/directory changes

### ISSUE THREAD

**Issue by kishaningithub** [spf13/afero#318]
In linux we have inotify
in osx we have fsevents
etc

Does this library offer abstraction over those as well?

**Comment by isopropylcyanide** [comment]
*Not a maintainer*

Afero doesn't provide a notification abstraction. What you are probably looking for is a File watcher/notifiers system like [fsnotify](https://github.com/fsnotify/fsnotify) to support mock file systems like Afero.

They have already discussed not implementing a mock file system notification https://github.com/fsnotify/fsnotify/issues/231

**Comment by kishaningithub** [comment]
Thanks for the answer @isopropylcyanide Closing this issue
