### ISSUE TITLE
Internalize some types used by MemMapFs

### ISSUE THREAD

**Issue by mbertschler** [spf13/afero#33]
I was just looking at afero in godoc and wondered about the exported types that are probably not used directly by users of the library as they only exist to support MemMapFs. I propose to unexport the following types for the sake of simplifying the API and focusing the documentation on the important parts of afero:

- `type InMemoryFile`
- `type InMemoryFileInfo`
- `type MemDir`
- `type MemDirMap`

Do you think that this is a good idea, or do you know any projects that use these types?

**Comment by mbertschler** [comment]
Another possible option would be to put them in a subpackage.

**Comment by bep** [comment]
Good idea, about the un-exporting.

**Comment by spf13** [comment]
The reason I made them public is so someone else can create a different memory backed storage backend without re-implementing these primitive types. 

I've had intent to create a radix tree backend, but others may want to do different things.

Does that make sense? We should probably at least add commentary around them explaining this.

**Comment by mbertschler** [comment]
It makes sense that way. But maybe then the subpackage approach would work? The Readme could link to the subpackage for people interested in the internals of the memory fs. 

I think that a simpler API in the main package and in the docs would improve the usability of afero. I for myself often don't read a lot of the Readme doc and jump straight to godoc. And from that view I would currently wonder how do I use a memory fs. Eg do I have to create a MemDir to use it?

**Comment by spf13** [comment]
subpackage would make sense.

**Comment by spf13** [comment]
Fixed by 5aa5058609437ae2c3380ded21a17de420418f14
