### ISSUE TITLE
OsFs not checking for permissions on Windows

### ISSUE THREAD

**Issue by staticdev** [spf13/afero#336]
How to reproduce:

```go
package main

import (
	"log"

	"github.com/spf13/afero"
)

func main() {
	folderName := "secret"
	fsys := afero.NewOsFs()
	fsys.Mkdir(folderName, 0700)
	afero.WriteFile(fsys, "secret/filename", []byte(""), 0700)

	_, err := fsys.Stat("secret/filename")
	if err != nil {
		log.Fatal(err)
	}
	fsys.Chmod("secret", 0000)
	_, err = fsys.Stat("secret/filename")
	if err != nil {
		log.Fatal(err)
	}
}
```

You should get the error on second Stat (which is the intended behavior since the `secret` folder has no read permissions). It works on Linux and Mac, but not on Windows.

**Comment by jxsl13** [comment]
this might be a Go standard library issue instead of an afero one. As it simply uses the os package.

**Comment by staticdev** [comment]
@jxsl13 fair enough, will close this one.
