### ISSUE TITLE
TestWalk fails on Windows

### ISSUE THREAD

**Issue by moorereason** [spf13/afero#34]
I know you just committed fixes for the Windows errors and AppVeyor appears happy, but I'm seeing errors on `TestWalk`:

```
$ go test -v github.com/spf13/afero
...
--- FAIL: TestWalk (0.00s)
        path_test.go:67: Walk outputs not equal!
        path_test.go:69: MemMapFS
        path_test.go:70: /tmp/afero afero 0 true <nil>
                \tmp\afero\test.txt test.txt 446 false <nil>

        path_test.go:69: OsFs
        path_test.go:70: /tmp/afero afero 0 true <nil>
                \tmp\afero\renamefrom renamefrom 4 false <nil>
                \tmp\afero\test.txt test.txt 446 false <nil>
```

I'm on Windows 7 with go1.5.1 windows/amd64.  I've run `go get -u -v github.com/spf13/afero` to make sure all dependencies are up-to-date.

It looks like you should be using `filepath.Join` and friends.

**Comment by mbertschler** [comment]
The problem in this case is this line:   
```
\tmp\afero\renamefrom renamefrom 4 false <nil>
```
This file seems to still be there in the OsFs from the rename test while the MemMapFs was reset.

**Comment by moorereason** [comment]
The `TestWalk` function needs to be updated to use cross-platform path construction and temp directories, but you're right.

There were stale files in `C:\tmp\afero` from previous runs of the tests.  Once I deleted that directory, the tests are successful.

**Comment by mbertschler** [comment]
Oh yes, all the other new test don't use that directory anymore.

Okay so I updated the `TestWalk` function to use the new cross platform test functions. This should work now. Could you please update and confirm? Thanks

**Comment by moorereason** [comment]
This issue is resolved.
