### ISSUE TITLE
Union mount

### ISSUE THREAD

**Issue by ccirello** [spf13/afero#39]
Is it possible to use some sort of union mount with this library?

**Comment by spf13** [comment]
It isn't yet, but it 100% could be and without much effort I would think. Someone just needs to provide the backend for it. Ideally it would be written to leverage existing backends so it would automatically support new backends when they are added.

**Comment by ccirello** [comment]
Challenge not accepted yet on my side. I will read the code more carefully and, hopefully, come up with a proposal PR.

**Comment by vetinari** [comment]
When the https://github.com/spf13/afero/pull/46 is merged, take a look in the filter*.go. The UnionFs then could be another filter like 
```go
    src := OsFs{}
    top := MemMapFs{}
    ufs := NewFilter(src)
    ufs.AddFilter(NewFsLayer(top))
```
which intercepts and merges the calls to the two Fs

**Comment by vetinari** [comment]
There's now a draft of a union fs in https://github.com/vetinari/afero/tree/unionfs The overlay can only be a MemMapFs currently, but else any kinds of Fs or FilterFs can be used as base layer and overlay. To support OsFs as overlay, we would need the suggested BasePath Fs.

Any comments on this?

**Comment by spf13** [comment]
What would be really cool is if we could stack unionfs on another unionfs. I'm not sure how practical it is, but I could see a network drive behind a disk behind memory. 

It may be worth experimenting with the new SFTP backend that @xor-gate worked on in #47

**Comment by vetinari** [comment]
The current implementation is a "copy on write" union. I think we should provide some kind of interface where NewUnionFs() accepts two Fs and an implementation specific constructor like
```go
  func NewUnionFs(baseFs Fs, layerFs Fs, impl func(Fs, Fs) FilterFs) FilterFs
```
where the ```impl``` could be something like
```go
func NewCacheUnionFs(t time.Duration) (func func(Fs, Fs) FilterFs) {
    return func(base Fs, layer Fs) FilterFs { 
          return &cfs{cacheTime: t, base: base, layer: layer}
    }
}
```
or just the current ```newCOWFilter```
-> 

```go
ufs := NewUnionFs(baseFs, layerFs, NewCacheUnionFs(1 * time.Minute))
```

**Comment by spf13** [comment]
I think that would be pretty useful.
I think time should be optional as I can see cases where people would want
this the entire life of the cacheFS.

**Comment by vetinari** [comment]
Updated the tree, the caching stuff is still a draft. For some calls it should be discussed what should happen:
* Mkdir / MkdirAll - leave like it is?
* Create / OpenFile - write changes also down to base layer?
* other write operations: ok, if we return the result to the overlay and ignore the results of the deferred call to the base?

**Comment by spf13** [comment]
Essentially it would make the first layer a buffer/ of the second (origin).
Meaning write operations would persist through it. Read operations would
pull from the origin of the cache is empty.

Changes to the origin wouldn't be reflected in the cache (a cache duration
option or flag could override) unless made through the cache layer first.

**Comment by vetinari** [comment]
https://github.com/spf13/afero/pull/50 should do it

**Comment by vetinari** [comment]
hmm, someone with access and knowledge on windows should check why the appveyor build fails. It may be due to https://github.com/spf13/afero/issues/51

**Comment by spf13** [comment]
Should these be written as FSs instead of filters? I guess I'm struggling a bit where the line is between them. It makes perfect sense to me in the case of ReadOnly, but these seem like that may be better as a standard FS.

**Comment by ccirello** [comment]
From what I've been using and Testing,  I side with the concept that union mount is a FS with an interface to bind more FS

**Comment by spf13** [comment]
@ccirello @vetinari I've updated the unions to be filesystems. Please see the updated readme and update your code.
