### ISSUE TITLE
Initial sftp backend draft

### ISSUE THREAD

**Issue by xor-gate** [spf13/afero#47]
Hi guys,

I'm fairly new with golang and trying to get my hands dirty and have got a initial working draft on a SFTP backend.

**What works**
* Connecting/disconnecting (with $HOME/.ssh/id_rsa)
* Creating and writing a file
* Most trivial functions

**What works not**
* Passing advanced SSH/sftp config

Here is a example:
```
        fs := new(afero.SftpFs)

        fs.Connect("user", "host:port")

        fs.Mkdir("foo", os.FileMode(0000))
        fs.Mkdir("bar", os.FileMode(0777))

        f, err := fs.Create("dusse")
        if err != nil {
                log.Fatalf("open: %v", err)
        }
        defer f.Close()

        f.Write([]byte("awesomeeeeee"))
       
        fs.MkdirAll("dir1/dir2/dir3", os.FileMode(0777))

        fs.Remove("dir1/dir2/dir3")
        fs.Remove("dir1/dir2")

        fs.Disconnect()
``` 

The thing lives currently in my forked branch to have some talking before I'm creating a pull request because I felt it is not ready to be merged yet.

https://github.com/xor-gate/afero/blob/sftp/sftp.go
https://github.com/xor-gate/afero/blob/sftp/sftp/file.go

Kind regards,
Jerry

**Comment by spf13** [comment]
Instead of having the connect and disconnect part of the fs, I think it would be much cleaner to pass the connected handle into the afero.SftpFs. 

See how this implementation of AferoS3 does it for inspiration. 

https://github.com/chonthu/aferoS3/blob/master/s3Fs.go

**Comment by xor-gate** [comment]
@spf13 thanks for your comments. I also wasn't satisfied but it was the quickest way to get it working. I have changed it to match the s3Fs implementation and added a test file.

See https://github.com/xor-gate/afero/commit/669780de6e465b29eab862efb9704d342961da02

**Comment by spf13** [comment]
Let's add some details in the readme about how to use this, call it beta, merge it in and get feedback from others?

**Comment by xor-gate** [comment]
I will close this because it kind of works now (beta) and the pull request needs some discussion.
