### ISSUE TITLE
Explain the difference between filter and filesystem better

### ISSUE THREAD

**Issue by spf13** [spf13/afero#58]
@vetinari The recent additions you've provided are great. Well written and thoughtfully done. In reading through the readme, it's not at all apparent what the difference is between a filter and a filesystem considering both adhere to the same interface. 

As I see it the main difference is that the filter is stackable at call time where any combination of filesystems as a filesystem needs to be predefined. It does beg the question though if everything should be a filter (or if we should incorporate that functionality into the FS since that's a compelling feature. 

If you could elaborate on the readme I'm sure many would benefit.

**Comment by mbertschler** [comment]
I would really like it if Filters could be normal filesystems as I didn't really get the difference between FilterFs and a normal Fs yet. Besides that I am always in favor of a simpler basic interface that is consistent with all filesystems. 

One more thing to consider is that its easier to switch between different Fss (eg OsFs, UnionFs) in your code if all implement the same interface. My point is that no matter if it is a Fs or a FilterFs, the result you want to achieve is the same.

**Comment by kofalt** [comment]
Agreed. Unless I'm fundamentally misunderstanding something, there is nothing a filter can do that couldn't be accomplished by an Fs that wraps another Fs. I liked the filter idea but am not currently convinced there's sufficient justification for a second type.

**Comment by spf13** [comment]
I'm glad it's not just me. 

I've given this a lot of thought this morning and I'll articulate my thoughts here. 

The notion of filtering is a pretty powerful concept. Filters can be applied at call time and are chainable. However we may just want to add that functionality directly to FS. In some ways we already have support for this in FS. There is one key semantic difference though. Filters are chain-able. FileSystems are embeddable. 

## Simple example

### Filter approach:
```
    ROFs := afero.NewFilter(AppFs)
    ROFs.AddFilter(afero.NewReadonlyFilter())
```

### Filesystem approach:
```
  ROFS := &afero.ReadOnlyFS{SourceFs: AppFS}
```

## More complicated Example


### Filter approach:
```
    ROFs := afero.NewFilter(AppFs)
    ROFs.AddFilter(afero.NewReadonlyFilter())
     re := regexp.MustCompile(`\.(\S*) `)
    ROFs.AddFilter(afero.NewRegexpFilter(*regexp.Regexp))
```

### Filesystem approach:
```
  ROFS := &afero.ReadOnlyFS{SourceFs: AppFS}
  re := regexp.MustCompile(`\.(\S*) `)
  RegROFS := &afero.RegExpFS{SourceFs: ROFS, RegEx: re}
```
or 
```
  re := regexp.MustCompile(`\.(\S*) `)
  RegROFS := &afero.RegExpFS{SourceFs: &afero.ReadOnlyFS{SourceFs: AppFS, RegEx: re}
```

I suggest we eliminate filters entirely as we already have the full set of functionality with FileSystems. 

I do think we should define some sane field names so that there is interoperatibility between similar filesystems. 

Just to explain and perhaps by way of suggestion I think the following would make sense.

Network (Handle or Connection) [s3, sftp, etc]
File (FileHandle) [zip, tar, etc]
Embedded (SourceFs) [httpFs, ReadOnlyFs, RegExpFs, etc]
DualEmbedded (BaseFs, LayerFS) [CopyOnWriteFs, CacheFs, MirrorFs]

I can't think of other types right now, but I think these cover the bases. Of course many of these filesystems would have unique extra fields. As they are fields we can't create an interface that enforces them but we can create types that can be easily embedded in the struct types that are defined though that would make it much more difficult to instantiate them as composite literals. So maybe the best approach is just to declare it as a convention.  

I've also noticed @vetinari has provided constructors for his Filters. Not sure how I feel about those. I don't feel they are necessary as the approach of using composite literals is much more Go like and we don't really benefit from the constructors. 

Another feature/issue with the filters is that they are dynamic. I see this as a real problem. I think the filesystem object should be immutable (a good argument for constructors). I really don't like the idea that at any point some piece of code can come along and apply a filter and change the behavior of a given FileSystem. As I think more and more about this, this is just as strong of a case for constructors as it is against filters.

Thoughts?

**Comment by vetinari** [comment]
I like the suggestion to remove the filters and go via the filesystem approach - maybe it was a blind spot on my side I did not see the way to do it as a "normal" file system.

The suggestions of these four types: what's the difference of a network handle/connection and a file handle? For me both looks just like an initialized data structure which is needed to operate on this specific data source. On the other hand, a file handle can usually be an io.ReadWriter, so we could e.g. hold a compressed archive in memory and operate on that one. A network handle is more complicated usually.

**Comment by kofalt** [comment]
I'm on board with Filter-like behaviours simply becoming Fs objects and not having strict requirements that distinguish an Fs from an Fs that happens to wrap an Fs. Convention seems the right way to go there.

@spf13 To clarify, are you thinking that `DualEmbedded` and etc would be an interface that an Fs could optionally implement? I'm not sure where you're going with those.

**Comment by moorereason** [comment]
If you build a composite literal with private fields, does it gain you much?  You can at least encourage immutable usage.

```go

RegROFS := &afero.RegExpFS{
    sourceFs: &afero.ReadOnlyFS{
        sourceFs: AppFS,
        regEx: regexp.MustCompile(`\.(\S*) `),
    }
}
```
`RegROFS.sourceFs` and its fields are inaccessible afterwards.

**Comment by spf13** [comment]
@kofalt @vetinari I'm not sure where I was going with those types, other than trying to enforce some basic conventions. I now suggest we do just that, enforce conventions.

@moorereason:
That's actually the perfect solution... or at least part of it.
To enforce immutability you would need to do the following..

```
var regROFS afero.FS

func RegROFS() {
    if regROFS == nil {
        regROFS := &afero.RegExpFS{
            sourceFs: &afero.ReadOnlyFS{
                sourceFs: AppFS,
                regEx: regexp.MustCompile(`\.(\S*) `),
            }
        }
    }

   return regROFS
}
```

I'm going to do the massive rewrite of things to merge in all @vetinari 's work and then port it to FileSystems. Then change things to be private fields and update Hugo to work with the latest Afero.

**Comment by bep** [comment]
> To enforce immutability you would need to do the following.

And to enforce thread-safety you would have to do something more/different.

**Comment by kofalt** [comment]
> I'm not sure where I was going with those types, other than trying to enforce some basic conventions. I now suggest we do just that, enforce conventions.

> I'm going to do the massive rewrite of things to merge in all @vetinari 's work and then port it to FileSystems.

SGTM :+1: 

> And to enforce thread-safety you would have to do something more/different.

I would disagree with efforts to make Fs construction / introspection thread-safe.

**Comment by spf13** [comment]
@bep Agreed. I was trying to illustrate that the immutable approach was sound (and the users responsibility). 

@kofalt Afero isn't responsible for Fs construction, it's the users responsibility to make it thread-safe if they so choose to.

**Comment by spf13** [comment]
Admittedly the filter interface is more convenient in this case
```
	mfs := &MemMapFs{}
	fs := NewFilter(mfs)
	fs.AddFilter(NewRegexpFilter(regexp.MustCompile(`\.txt$`)))
	fs.AddFilter(NewRegexpFilter(regexp.MustCompile(`^a`)))
```

But since it has to pass through both filters, I'm ok with the interface that feels like it's more explicitly doing that:

```
	mfs := &MemMapFs{}
	fs1 := &RegexpFs{re: regexp.MustCompile(`\.txt$`), source: mfs}
	fs := &RegexpFs{re: regexp.MustCompile(`^a`), source: fs1}
```

I'm nearly done. There's very little difference between a filter and filesystem and @vetinari 's work is very well done so it's pretty painless.
