### ISSUE TITLE
Sftp_test has errors

### ISSUE THREAD

**Issue by spf13** [spf13/afero#59]
```
./sftp_test.go:203: cannot use debugStream (type io.Writer) as type string in argument to sftp.NewServer
./sftp_test.go:203: cannot use debugLevel (type int) as type sftp.ServerOption in argument to sftp.NewServer
./sftp_test.go:203: cannot use readOnly (type bool) as type sftp.ServerOption in argument to sftp.NewServer
./sftp_test.go:203: cannot use rootpath (type string) as type sftp.ServerOption in argument to sftp.NewServer
```

I'm not sure if it's just me, but this doesn't look like it should have ever built. If I'm doing something wrong, please let me know.

**Comment by xor-gate** [comment]
It did work, those guys started to break the master branch exactly 6 days ago:

https://github.com/pkg/sftp/commits/master

<img width="1025" alt="screen shot 2016-01-17 at 22 24 59" src="https://cloud.githubusercontent.com/assets/1050166/12380059/417b56c0-bd69-11e5-9d9a-c6c3dc746536.png">

**Comment by spf13** [comment]
Doh. We need to vendor these deps.

**Comment by kargakis** [comment]
Fixed by https://github.com/spf13/afero/pull/157
