### ISSUE TITLE
Any specific reason a Walk function is not implemented within the package?

### ISSUE THREAD

**Issue by srinathh** [spf13/afero#6]
I can see that Fs interface doesn't specify LStat which is used in the implementation of Walk in the standard library so any Walk implementation on afero would not be 100% compatible with the standard library

However, Walk is a very common requirement for filesystems and so I wonder if there's a specific reason afero chooses not to provide one. If no, would it be ok for me to add an implementation & file a pull request?

**Comment by bep** [comment]
It would be most welcomed.

I wondered this myself. Hugo uses afero and does a lot walking ...
