### ISSUE TITLE
extend CopyOnWriteFs to be able to use other backends as an overlay

### ISSUE THREAD

**Issue by spf13** [spf13/afero#60]
Currently CopyOnWriteFs can only use MemMapFs as a backend on the overlay.

It would be great to be able to use other backends. Specifically it's very useful to have two directories on disk layered with one of them being writable. This is easily accomplished using BasePathFs and OsFs but we need support for it in CoWFs.

**Comment by spf13** [comment]
@vetinari do you want to look into this now that I've finished porting the backends over?

**Comment by vetinari** [comment]
@spf13 I'll do that, not sure when there's time for this  - I'm busy with other stuff currently

**Comment by spf13** [comment]
Is the only thing missing the mkdirAll calls? Even just some guidance on
what needs to be done would be very helpful.

**Comment by vetinari** [comment]
Looks like the most MkdirAll calls mentioned in the comments and the README are in the `copyToLayer()`. The ones missing are probably in `OpenFile()` and `Create()` when opening a file for writing which does not exist in both layers but the directory in the base exists.

**Comment by vetinari** [comment]
changes done in https://github.com/spf13/afero/pull/62
