### ISSUE TITLE
release

### ISSUE THREAD

**Issue by joeblew99** [spf13/afero#70]
Is this library stable ? Just noticed that there have not been any releases yet and so thought i should ask.

I actually need the SFTP functionality.

**Comment by mbertschler** [comment]
I think afero is not considered stable yet.
Especially our SFTP dependency is changing: https://github.com/pkg/sftp/issues/86
and in here: #59 we concluded we need to vendor this dependency.
I think if our vendoring problem is solved and this gets fixed: #64 then we can tag a release.

**Comment by joeblew99** [comment]
ok makes sense thanks.

i will just use the sftp package for now and watch out for changes.

thanks allot.
