### ISSUE TITLE
How to vendor our dependencies?

### ISSUE THREAD

**Issue by mbertschler** [spf13/afero#72]
@spf13 What process should we use to vendor our dependencies?

Now that Go 1.6 is released and vendoring is enabled by default we should use something that uses the `/vendor` subdirectory approach. Should we use a tool for that or just make a subtree merge with squashed commits?

The reason why we should vendor is for example this issue: #59

**Comment by xor-gate** [comment]
This option is also available for Go 1.5 when enable manually. I don't know which version we should support as minimal ?

**Comment by mkishere** [comment]
Hi when trying to pass the PR #154 found out that CI could not compile for Go 1.7.5, and found that the guys at [sftp package](https://github.com/pkg/sftp) already dropped support for versions below 1.8. We should start using dependency management tool ASAP. I suggest we should use [dep](https://github.com/golang/dep) and check in the vendor directory.

**Comment by kargakis** [comment]
go modules are used now
