### ISSUE TITLE
sftp_test_go

### ISSUE THREAD

**Issue by joeblew99** [spf13/afero#74]
I assume this is failing ?
I am needing to connect to a sftp server, that does not use ssh key pair, and thought i woudl give this a try, but the fact that the test for SFTP is stubbed out makes me think its stubbed out because it is not ready.

The test is trying to setup a local SFTP server. I am working against this SFTP server.
http://docs.ipswitch.com/WS_FTP_Server71/ReleaseNotes/index.htm?k_id=ipswitch_com_ftp_documents_worldwide_ws_ftpserverv71releasenotes

Can you let me know please.

**Comment by joeblew99** [comment]
The current test (TestSftpCreate) that fires up a local SFTP server passes. Yeeha.

Now i am trying to connect to a Remote server with the exact same test code, adapted with the credentials.
This is the remote server type:
http://docs.ipswitch.com/WS_FTP_Server71/ReleaseNotes/index.htm?k_id=ipswitch_com_ftp_documents_worldwide_ws_ftpserverv71releasenotes

This code:
```
ctx, err := SftpConnect(user, password, host)
	if err != nil {
		t.Fatal(err)
	}

``` 

Errors with:
````
sftp_test.go:313: ssh: handshake failed: ssh: no common algorithm for client to server cipher; client offered: [aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128], server offered: [3des-cbc blowfish-cbc aes256-cbc aes128-cbc cast128-cbc]

```

So its telling me not to try with RSA; but instead use Blowfish cipher ?
Note that i am not using any ssh keys, but just connecting with username, password, host.

Any tip son this really welcome...

**Comment by mbertschler** [comment]
@xor-gate, do you have any information on this as you wrote the sftp backend?

**Comment by xor-gate** [comment]
@mbertschler here I will the private email conversation:

> Hi Joe,
> 
> No problem for contacting me. I have only tested this against OpenSSH and Golang SFTP server itself. Keep in mind it is possible your closed source WS_FTP server probably only implements filetransfer over SSH and probably not with the SFTP protocol. You must make sure the ciphersuites are supported on your client which are default (or configured) on your server. It also depends how you configure your ssh/sftp server to use ssh keys or passwords, or mixed. I can only speak for OpenSSH and you should consult your configuration of WS_FTP and documentation. Have you tried sftp client with OpenSSH,Cyberduck or Filezilla. What you probably can do to have a very detailed view of what happens you should try to sftp with OpenSSH tool in extreme verbose mode with -vvv (see http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/sftp.1?query=sftp&sec=1)
> 
> My conclusion: first try with already working tools and investigate the actual handshaking and ciphersuites etc and the proceed to try this in golang.
> 
> If you get stuck at a different point i'm willing to support you but no guarantees I can fully help you :-)
> 
> Good luck,
> 
> Kind regards,
> Jerry

**Comment by xor-gate** [comment]
@joeblew99 it seems your issue/error is exactly what I suggested:

```
sftp_test.go:313: ssh: handshake failed: ssh: no common algorithm for client to server cipher; client offered: [aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128], server offered: [3des-cbc blowfish-cbc aes256-cbc aes128-cbc cast128-cbc]
```

It means Golang sftp/ssh client encryption ciphers offered `aes*-ctr` and the WSFTP server only accepts `aes*-cbc`. So basicly this means the SSH/SFTP golang lib needs to have CBC (Cipher Block Chaining) or blowfish-cbc support.

**Comment by joeblew99** [comment]
Thanks all.
I emailed the team doing sftp / SSH but have heard nothing.
So I guess its not a high priority for them, since it is one of the older
ciphers apparently

**Comment by joeblew99** [comment]
I will close it here. It's nothing to do with afero

**Comment by xor-gate** [comment]
Good luck @joeblew99 !

**Comment by joeblew99** [comment]
Thanks. I resorted to calling out to filezilla library. That's life
sometime :)
