### ISSUE TITLE
CopyOnWriteFs fails to CreateFile

### ISSUE THREAD

**Issue by pgruenbacher** [spf13/afero#78]
I was getting stat IsNotExist errors when doing a MkdirAll followed by a an OpenFile. It seemed that that CopyOnWriteFs was checking the base os first to see if the base directory of the opened file IsDir, but that led to a stat error being returned. 

line in question:
https://github.com/spf13/afero/blob/master/copyOnWriteFs.go#L149

my quick solution.
```
        dir := filepath.Dir(name)
        var isaDir bool
        if isaDir, err = IsDir(u.base, dir); os.IsNotExist(err) {
            // skip ahead
        } else if err != nil {
            return nil, err
        }
        if isaDir {
            if err = u.layer.MkdirAll(dir, 0777); err != nil {
                return nil, err
            }
            return u.layer.OpenFile(name, flag, perm)
        }  
```

**Comment by mbertschler** [comment]
@pgruenbacher could you please provide a quick code example on how to trigger this bug?

**Comment by pgruenbacher** [comment]
https://github.com/spf13/afero/pull/81
