### ISSUE TITLE
Unable to "chain" BasePathFs

### ISSUE THREAD

**Issue by francoishill** [spf13/afero#79]
This example does not work as expected:

```
package main

import (
	"fmt"

	"github.com/spf13/afero"
)

func main() {
	fs1 := afero.NewBasePathFs(afero.NewOsFs(), "/dir1/subdir1")
	fmt.Println(fs1.(*afero.BasePathFs).RealPath("file.txt"))
	fs2 := afero.NewBasePathFs(fs1, "/dir2/subdir2")
	fmt.Println(fs2.(*afero.BasePathFs).RealPath("file.txt"))
}
```

The above output is:

```
/dir1/subdir1/file.txt
/dir2/subdir2/file.txt
```

Instead I expected `fs2` to have nested paths as it uses `fs1` as its source:

```
/dir1/subdir1/file.txt
/dir1/subdir1/dir2/subdir2/file.txt
```

**Comment by vetinari** [comment]
If the example would print the nested path, an app which just gets the fs2 from your example above, would be able to reveal too much about the system, IMO. 
If all agree to extend the RealPath() to check for the base's type and call then that RealPath(), I can add it (@spf13 , @mbertschler please :))

**Comment by francoishill** [comment]
Your point makes sense. The problem, however, is that the `RealPath` method is used by all other api methods (like `Mkdir`, `Open`, etc). Regarding your concern, perhaps make the `RealPath` method private?

Before reading your comment I did however implement pull request [80](https://github.com/spf13/afero/pull/80) to resolve this.

**Comment by mbertschler** [comment]
Hmm... #80 looks nice and works, but the security issue is probably also a valid point. Maybe we could leave the RealPath() behaviour like this, but add a private fullPath() method that works like in your pull request and then replace all internal usages of RealPath() with this?

**Comment by francoishill** [comment]
Sure, I like that
