### ISSUE TITLE
File not found when parent directory not present

### ISSUE THREAD

**Issue by tischda** [spf13/afero#86]
In `copyOnWriteFs.go` you test if the file is not found in the layer Fs, but if the parent directory is not present either, you will get `syscall.ENOTDIR` instead of `syscall.ENOENT`. This only happens on Windows, you can find background information here: https://codereview.appspot.com/4984051/

A solution could be to replace line 35 with:
`if oerr.Err == os.ErrNotExist || oerr.Err == syscall.ENOENT || oerr.Err == syscall.ENOTDIR {`

and change the test at line 83:
```
if err == syscall.ENOENT || err == syscall.ENOTDIR {
	return u.base.Stat(name)
}
```

This should fix the failing unit test and solve an issue in Hugo where CSS is not copied from the theme if your site `static` directory does not already contain a `css` directory.

**Comment by bep** [comment]
Thanks for this report.
