### ISSUE TITLE
Symlink handling in BasePathFs

### ISSUE THREAD

**Issue by ashb** [spf13/afero#88]
I would like to use Afero's BasePathFs to simluate a chroot-like environment any I was unsure how you'd handle symlinks.

For example, if I have `bin/foo` Symlinks to `/usr/bin/bar` and then I put both these files in `/tmp/afero-test` and try to run this:

``` go
bp := afero.NewBasePathFs(afero.NewOsFs(), "/tmp/afero-test")
fh, err := bp.Open("/bin/foo")
```

Do i get an error? (I think right now I do) I'd kind of like this to "rewrite" the symlinks so that I actually open `/tmp/afero-test/usr/bin/bar`. Would this be an acceptable change to make?

(Is supporting symlinks in one type of FS but not others going to cause problems?)

**Comment by kargakis** [comment]
Symlink support added in https://github.com/spf13/afero/pull/228
